compute_environment: LOCAL_MACHINE
deepspeed_config: {}
distributed_type: MULTI_GPU
fp16: true
machine_rank: 0
main_process_ip: null
main_process_port: null
num_machines: 1
num_processes: 2  # 사용 가능한 GPU 수에 맞게 수정
